# Generated by Django 5.1.5 on 2025-01-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(related_name='tasks', to='api.contact'),
        ),
    ]
